import { colors } from '@/src/themes'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        elevation: 2,
        shadowColor: colors.gray600,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.text,
    },
    calendarContainer: {
        marginHorizontal: 16,
        marginTop: 12,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        elevation: 3,
        shadowColor: colors.gray600,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    statsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
    },
    statCard: {
        flex: 1,
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        elevation: 2,
        shadowColor: colors.gray600,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: '500',
        color: colors.textSecondary,
        marginBottom: 4,
    },
    statValue: {
        fontSize: 22,
        fontWeight: '700',
        color: colors.text,
    },
    statValueHighlight: {
        color: colors.primary,
    },
    legendContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 24,
        paddingVertical: 12,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    legendDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    legendText: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    todayButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: colors.primary,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
    },
    todayButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.white,
    },
    infoContainer: {
        marginHorizontal: 16,
        marginTop: 8,
        marginBottom: 24,
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    infoTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 8,
    },
    infoText: {
        fontSize: 13,
        color: colors.textSecondary,
        lineHeight: 20,
    },
    // Day detail
    dayDetailContainer: {
        marginHorizontal: 16,
        marginTop: 12,
        marginBottom: 24,
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.border,
        elevation: 2,
        shadowColor: colors.gray600,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    dayDetailHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    dayDetailTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text,
    },
    addEntryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: colors.success,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
    },
    addEntryButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.white,
    },
    entryCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.gray50,
        borderRadius: 10,
        padding: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    entryIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#e0e7ff',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    entryContent: {
        flex: 1,
    },
    entryCompany: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
    },
    entryAmount: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.success,
        marginTop: 2,
    },
    entryDelete: {
        padding: 6,
    },
    dayTotalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: colors.border,
        paddingTop: 12,
        marginTop: 4,
    },
    dayTotalLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.textSecondary,
    },
    dayTotalValue: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.primary,
    },
    emptyDay: {
        alignItems: 'center',
        paddingVertical: 24,
        gap: 8,
    },
    emptyDayText: {
        fontSize: 13,
        color: colors.textSecondary,
    },
    // Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.surface,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 24,
        paddingBottom: 40,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.text,
    },
    inputLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.textSecondary,
        marginBottom: 6,
        marginTop: 12,
    },
    input: {
        backgroundColor: colors.gray50,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 15,
        color: colors.text,
    },
    modalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: colors.success,
        borderRadius: 12,
        paddingVertical: 14,
        marginTop: 24,
    },
    modalButtonText: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.white,
    },
})
